[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "www"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
